name: "✨ 機能要望"
description: "新機能・改善の提案"
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: 背景/課題
      description: どんな課題を解決したいか。
      placeholder: 例) EQプロファイルの検索性が低い
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 提案
      description: どう解決したいか（UI/CLI/APIなど）。
      placeholder: 例) ベンダー・製品名での部分一致検索を追加する
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他の案があれば。

  - type: textarea
    id: context
    attributes:
      label: 追加コンテキスト
      description: 参考リンク・スクリーンショット等。

